// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CustomerVoucher struct {
	ID         int32            `json:"id"`
	CustomerID string           `json:"customer_id"`
	VoucherID  int32            `json:"voucher_id"`
	Status     pgtype.Text      `json:"status"`
	UsedAt     pgtype.Timestamp `json:"used_at"`
}

type LoyaltyPoint struct {
	ID          int32            `json:"id"`
	CustomerID  string           `json:"customer_id"`
	Points      pgtype.Int4      `json:"points"`
	Source      string           `json:"source"`
	ReferenceID pgtype.Int4      `json:"reference_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type UsageRecord struct {
	CustomerID string           `json:"customer_id"`
	VoucherID  int32            `json:"voucher_id"`
	OrderID    int32            `json:"order_id"`
	Status     pgtype.Text      `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Voucher struct {
	ID            int32            `json:"id"`
	Code          string           `json:"code"`
	Description   pgtype.Text      `json:"description"`
	DiscountType  string           `json:"discount_type"`
	DiscountValue pgtype.Numeric   `json:"discount_value"`
	StartDate     pgtype.Date      `json:"start_date"`
	EndDate       pgtype.Date      `json:"end_date"`
	UsageLimit    pgtype.Int4      `json:"usage_limit"`
	IsGlobal      pgtype.Bool      `json:"is_global"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}
