// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateCustomerVoucher(ctx context.Context, arg CreateCustomerVoucherParams) (CustomerVoucher, error)
	CreateLoyaltyPoint(ctx context.Context, arg CreateLoyaltyPointParams) (LoyaltyPoint, error)
	CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error)
	DeleteCustomerVoucher(ctx context.Context, id int32) error
	DeleteLoyaltyPoint(ctx context.Context, id int32) error
	DeleteVoucher(ctx context.Context, id int32) error
	GetActiveVouchers(ctx context.Context, arg GetActiveVouchersParams) ([]Voucher, error)
	GetAllCustomerVouchers(ctx context.Context, arg GetAllCustomerVouchersParams) ([]GetAllCustomerVouchersRow, error)
	GetAllLoyaltyPoints(ctx context.Context, arg GetAllLoyaltyPointsParams) ([]LoyaltyPoint, error)
	GetAllVouchers(ctx context.Context, arg GetAllVouchersParams) ([]Voucher, error)
	GetAvailableVouchersForCustomer(ctx context.Context, arg GetAvailableVouchersForCustomerParams) ([]Voucher, error)
	GetCustomerTotalPoints(ctx context.Context, customerID int32) (interface{}, error)
	GetCustomerVoucher(ctx context.Context, id int32) (CustomerVoucher, error)
	GetCustomerVouchers(ctx context.Context, arg GetCustomerVouchersParams) ([]GetCustomerVouchersRow, error)
	GetCustomerVouchersByStatus(ctx context.Context, arg GetCustomerVouchersByStatusParams) ([]GetCustomerVouchersByStatusRow, error)
	GetLoyaltyPoint(ctx context.Context, id int32) (LoyaltyPoint, error)
	GetLoyaltyPointsByCustomer(ctx context.Context, arg GetLoyaltyPointsByCustomerParams) ([]LoyaltyPoint, error)
	GetLoyaltyPointsBySource(ctx context.Context, arg GetLoyaltyPointsBySourceParams) ([]LoyaltyPoint, error)
	GetVoucher(ctx context.Context, id int32) (Voucher, error)
	GetVoucherByCode(ctx context.Context, code string) (Voucher, error)
	UpdateCustomerVoucherStatus(ctx context.Context, arg UpdateCustomerVoucherStatusParams) (CustomerVoucher, error)
	UpdateLoyaltyPoints(ctx context.Context, arg UpdateLoyaltyPointsParams) (LoyaltyPoint, error)
	UpdateVoucher(ctx context.Context, arg UpdateVoucherParams) (Voucher, error)
	UseCustomerVoucher(ctx context.Context, arg UseCustomerVoucherParams) (CustomerVoucher, error)
}

var _ Querier = (*Queries)(nil)
