CREATE TABLE "gold_prices" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" timestamp,
  "gold_id" INT NOT NULL,
  "gold_type" varchar(50) NOT NULL,
  "buy_price" decimal(15,2) NOT NULL,
  "sell_price" decimal(15,2) NOT NULL
);

CREATE TABLE "buyback_policies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_type" varchar(100) NOT NULL,
  "buyback_rate" decimal(5,2) NOT NULL,
  "description" text,
  "created_at" timestamp
);