package consts

var (
	EXCHANGE_PRODUCT_SERVICE string = "EXCHANGE_PRODUCT_SERVICE"
	EXCHANGE_ORDER_SERVICE   string = "EXCHANGE_ORDER_SERVICE"
	EXCHANGE_AUTH_SERVICE    string = "EXCHANGE_AUTH_SERVICE"
)
