CREATE TABLE "loyalty_points" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int NOT NULL,
  "points" int DEFAULT 0,
  "source" varchar(50) NOT NULL,
  "reference_id" int,
  "created_at" timestamp
);

CREATE TABLE "vouchers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL UNIQUE,
  "description" text,
  "discount_type" varchar(20) NOT NULL,
  "discount_value" decimal(15,2) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "usage_limit" int DEFAULT 1,
  "created_at" timestamp
);

CREATE TABLE "customer_vouchers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int NOT NULL,
  "voucher_id" int NOT NULL ,
  "status" varchar(20) DEFAULT 'unused',
  "used_at" timestamp
);

CREATE TABLE "usage_records" (
  "customer_id" int NOT NULL,
  "voucher_id" int NOT NULL,
  "order_id" int NOT NULL,
  "status" varchar(20) DEFAULT "pending", -- "pending", "used"
  "created_at" timestamp,
  "updated_at" timestamp

  ("customer_id", "voucher_id", "order_id")
);

ALTER TABLE "customer_vouchers" ADD FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id");

ALTER TABLE "usage_records" ADD FOREIGN KEY ("customer_id") REFERENCES "customer_vouchers" ("id");
ALTER TABLE "usage_records" ADD FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id");

