CREATE TABLE "product_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "code" varchar(50) UNIQUE NOT NULL,
  "category_id" int NOT NULL,
  "weight" decimal(10,2) NOT NULL,
  "gold_price_at_time" decimal(15,2) NOT NULL,
  "labor_cost" decimal(15,2) NOT NULL,
  "stone_cost" decimal(15,2) DEFAULT 0,
  "markup_rate" decimal(5,2) NOT NULL,
  "selling_price" decimal(15,2) NOT NULL,
  "warranty_period" int DEFAULT 0,
  "image" varchar(255) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "phone" varchar(20) UNIQUE NOT NULL,
  "email" varchar(255),
  "address" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "product_categories" ("id");
