CREATE TABLE "product_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "code" varchar(50) UNIQUE NOT NULL,
  "category_id" int,

  "stock" int,
  "buy_turn" int DEFAULT 0,

  "weight" decimal(10,2),
  "gold_price_at_time" decimal(15,2),
  "labor_cost" decimal(15,2),
  "stone_cost" decimal(15,2) DEFAULT 0,
  "markup_rate" decimal(5,2),
  "selling_price" decimal(15,2),
  "warranty_period" int DEFAULT 0,
  "image" varchar(255),

  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "phone" varchar(20) UNIQUE NOT NULL,
  "email" varchar(255),
  "address" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "order_record" (
  "customer_id" int NOT NULL,
  "product_id" int NOT NULL,
  "order_id" int NOT NULL,
  "quantity" int NOT NULL,
  
  "status" varchar(20) NOT NULL DEFAULT 'pending', -- "pending", "ordered"

  "created_at" timestamp,
  "updated_at" timestamp,

  PRIMARY KEY ("customer_id", "product_id", "order_id")
);

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "product_categories" ("id");
ALTER TABLE "order_record" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
ALTER TABLE "order_record" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");