// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Email     pgtype.Text      `json:"email"`
	Address   pgtype.Text      `json:"address"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type OrderRecord struct {
	CustomerID string           `json:"customer_id"`
	ProductID  int32            `json:"product_id"`
	OrderID    int32            `json:"order_id"`
	Quantity   int32            `json:"quantity"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID              int32            `json:"id"`
	Name            pgtype.Text      `json:"name"`
	Code            string           `json:"code"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	Stock           pgtype.Int4      `json:"stock"`
	BuyTurn         pgtype.Int4      `json:"buy_turn"`
	Weight          pgtype.Numeric   `json:"weight"`
	GoldPriceAtTime pgtype.Numeric   `json:"gold_price_at_time"`
	LaborCost       pgtype.Numeric   `json:"labor_cost"`
	StoneCost       pgtype.Numeric   `json:"stone_cost"`
	MarkupRate      pgtype.Numeric   `json:"markup_rate"`
	SellingPrice    pgtype.Numeric   `json:"selling_price"`
	WarrantyPeriod  pgtype.Int4      `json:"warranty_period"`
	Image           pgtype.Text      `json:"image"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type ProductCategory struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
