// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Email     pgtype.Text      `json:"email"`
	Address   pgtype.Text      `json:"address"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	Code            string           `json:"code"`
	CategoryID      int32            `json:"category_id"`
	Weight          pgtype.Numeric   `json:"weight"`
	GoldPriceAtTime pgtype.Numeric   `json:"gold_price_at_time"`
	LaborCost       pgtype.Numeric   `json:"labor_cost"`
	StoneCost       pgtype.Numeric   `json:"stone_cost"`
	MarkupRate      pgtype.Numeric   `json:"markup_rate"`
	SellingPrice    pgtype.Numeric   `json:"selling_price"`
	WarrantyPeriod  pgtype.Int4      `json:"warranty_period"`
	Image           string           `json:"image"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type ProductCategory struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
