// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteCustomer(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	GetCustomerByID(ctx context.Context, id int32) (Customer, error)
	GetCustomerByPhone(ctx context.Context, phone string) (Customer, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
