// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrderRecord(ctx context.Context, arg CreateOrderRecordParams) (OrderRecord, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, name string) (ProductCategory, error)
	DeleteCustomer(ctx context.Context, id int32) error
	DeleteOrderRecord(ctx context.Context, arg DeleteOrderRecordParams) (OrderRecord, error)
	DeleteProduct(ctx context.Context, id int32) error
	DeleteProductCategory(ctx context.Context, id int32) error
	GetCustomerByID(ctx context.Context, id int32) (Customer, error)
	GetCustomerByPhone(ctx context.Context, phone string) (Customer, error)
	GetOrderRecord(ctx context.Context, arg GetOrderRecordParams) (OrderRecord, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	GetProductCategoryByID(ctx context.Context, id int32) (ProductCategory, error)
	GetProductCategoryByName(ctx context.Context, name string) (ProductCategory, error)
	GetProductsById(ctx context.Context, dollar_1 []int32) ([]Product, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListOrderRecords(ctx context.Context, arg ListOrderRecordsParams) ([]OrderRecord, error)
	ListProductCategories(ctx context.Context) ([]ProductCategory, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateOrderRecord(ctx context.Context, arg UpdateOrderRecordParams) (OrderRecord, error)
	UpdateProductByCode(ctx context.Context, arg UpdateProductByCodeParams) (Product, error)
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
}

var _ Querier = (*Queries)(nil)
