// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BuybackPolicy struct {
	ID          int32            `json:"id"`
	ProductType string           `json:"product_type"`
	BuybackRate pgtype.Numeric   `json:"buyback_rate"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type GoldPrice struct {
	ID        int32            `json:"id"`
	Date      pgtype.Timestamp `json:"date"`
	GoldID    int32            `json:"gold_id"`
	GoldType  string           `json:"gold_type"`
	BuyPrice  pgtype.Numeric   `json:"buy_price"`
	SellPrice pgtype.Numeric   `json:"sell_price"`
}
