// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CountBuybackPolicies(ctx context.Context) (int64, error)
	CountBuybackPoliciesByProductType(ctx context.Context, productType string) (int64, error)
	CountGoldPrices(ctx context.Context) (int64, error)
	CountGoldPricesByType(ctx context.Context, goldType string) (int64, error)
	CreateBuybackPolicy(ctx context.Context, arg CreateBuybackPolicyParams) (BuybackPolicy, error)
	CreateGoldPrice(ctx context.Context, arg CreateGoldPriceParams) (GoldPrice, error)
	DeleteBuybackPolicy(ctx context.Context, id int32) error
	DeleteGoldPrice(ctx context.Context, id int32) error
	GetActiveBuybackPolicies(ctx context.Context, arg GetActiveBuybackPoliciesParams) ([]BuybackPolicy, error)
	GetBuybackPolicies(ctx context.Context, arg GetBuybackPoliciesParams) ([]BuybackPolicy, error)
	GetBuybackPoliciesByProductType(ctx context.Context, arg GetBuybackPoliciesByProductTypeParams) ([]BuybackPolicy, error)
	GetBuybackPolicy(ctx context.Context, id int32) (BuybackPolicy, error)
	GetGoldPrice(ctx context.Context, id int32) (GoldPrice, error)
	GetGoldPrices(ctx context.Context, arg GetGoldPricesParams) ([]GoldPrice, error)
	// ===== ADDITIONAL USEFUL QUERIES =====
	GetGoldPricesByDateRange(ctx context.Context, arg GetGoldPricesByDateRangeParams) ([]GoldPrice, error)
	GetGoldPricesByType(ctx context.Context, arg GetGoldPricesByTypeParams) ([]GoldPrice, error)
	GetGoldPricesWithHighestBuyPrice(ctx context.Context, arg GetGoldPricesWithHighestBuyPriceParams) ([]GoldPrice, error)
	GetLatestGoldPrices(ctx context.Context, arg GetLatestGoldPricesParams) ([]GoldPrice, error)
	SearchBuybackPoliciesByProductType(ctx context.Context, arg SearchBuybackPoliciesByProductTypeParams) ([]BuybackPolicy, error)
	SearchGoldPricesByType(ctx context.Context, arg SearchGoldPricesByTypeParams) ([]GoldPrice, error)
	UpdateBuybackPolicy(ctx context.Context, arg UpdateBuybackPolicyParams) (BuybackPolicy, error)
	UpdateBuybackRate(ctx context.Context, arg UpdateBuybackRateParams) (BuybackPolicy, error)
	UpdateGoldPrice(ctx context.Context, arg UpdateGoldPriceParams) (GoldPrice, error)
}

var _ Querier = (*Queries)(nil)
